lispgames/cl-sdl2

src/keyboard.lisp, src/mouse.lisp, src/package.lisp
These functions are useful for querying mouse and keyboard state outside the usual event poll mechanism.
=> Add a nice interface to SDL_GetKeyboardState and SDL_GetMouseState

src/package.lisp, src/video.lisp
Hello,
I found that I needed to get the display modes, so I exposed some of those functions. I'm happy to go back and forth with this, as I am not 100% sure that I implemented these things in a way that jives with the rest of the codebase.
In particular, get-display-mode does a multiple value return... I could think of a couple of different ways to do this, but didn't know which one was a better fit for Common Lisp.
=> Added a handful of video functions

src/package.lisp, src/surface.lisp
I needed a way to access the raw pixel data from an sdl-surface that was created from a call to sdl2-image:load-image to texture a quad using opengl. I noticed that while accessors for width and height were available there wasn't any for the pixels field of the struct.
Thought this might be helpful for others
=> Added an accessor function to get a pointer to an sdl-surface's raw pixel data

src/package.lisp, src/render.lisp
I'm not sure about renderer-get-viepower function: should I call ```(sdl-collect rect)``` before returning rect?
=> Add RENDER-{GET,SET}-VIEWPORT

sdl2.asd, src/package.lisp, src/pixels.lisp, src/rwops.lisp, src/surface.lisp
Added a way to create wrapped RWOPs structures which is helpful for some added functionality in cl-sdl2-image. Also surface-format-format returned a struct instead of an integer which gives the enum value of a surface
=> Added wrapped rwops data structure, fixed surface-format-format return value bug, added a method to see surface pixel format type for debug purposes

src/keyboard.lisp, src/package.lisp, src/video.lisp
Both functions are simple and currently used in my game engine project.
get-window-aspect-ratio can be used as input for the perspective GL matrix.
scancode-symbol returns the symbol associated with the number, e.g. (sdl2:scancode-symbol 43) returns :SCANCODE-TAB
I fixed the merge issues with pull request #61 by using the up to date cl-sdl2 and doing the changes again in a new commit.
=> Move two very useful functions into the upstream cl-sdl2 project.

src/rect.lisp
The branches in `with-rects` are in the wrong order, so the macro doesn't work.
```
CL-USER> (sdl2:with-rects () foo)
; in: SDL2:WITH-RECTS ()
;     (LET ((NIL (SDL2:MAKE-RECT 0 0 0 0)))
;       (SDL2:WITH-RECTS NIL
;         FOO))
; 
; caught ERROR:
;   NIL names a defined constant, and cannot be used as a local variable.
CL-USER> (macroexpand-1 '(sdl2:with-rects (foo) foo))
(PROGN FOO)
T
```
=> Fix with-rects

src/keyboard.lisp, src/package.lisp
There are some cases where people need scancode-key-to-value, but it was used directly twice in keyboard.lisp without being defined as a function and exported. Also, these conversion functions need documentation because they can cause confusion.
=> Add a missing function and document a very confusing section

src/mouse.lisp
This is a very simple fix. Right now, toggle-relative-mouse-mode errors because it's sending a CL nil or t where a C 0 or 1 is expected.
=> Fix toggle-relative-mouse-mode

sdl2.asd
hello! thanks for this repo. i need `SDL2:GET-WINDOW-WM-INFO` and noticed the file it was defined was not declared as part of the system. this patch adds the declaration :+1:
=> declare syswm as part of system

src/package.lisp
Sometime it is valuable to asdf:load-system with :force t in order to
find warnings. However due to the design of defpackage this will error
as many of the symbols exported for sdl2-ffi* are exported by
c-include.
By moving to define-package we avoid this issue.
Fixes https://github.com/lispgames/cl-sdl2/issues/95
=> Use define-package instead of defpackage for ffi packages

src/package.lisp, src/rect.lisp
Add accessors for point object and export them. Before, it was impossible to get the 'x' and 'y' values of a point object without using FFI functions.
=> Add Accessors for Point Object

src/autowrap.lisp
Without this it won't be able to generate a proper spec file
=> Add /usr/X11R6/include to sysincludes on openbsd

src/sdl2.lisp, src/video.lisp
+ added a check-not-below macro
Per [documentation](https://wiki.libsdl.org/SDL_GL_GetSwapInterval), `SDL_GL_GetSwapInterval` can return `-1` when "late swaps happen immediately instead of waiting for the next retrace". It's a valid return value that should not signal an error.
=> Fix for allowed return values of #'gl-get-swap-interval.

examples/renderer.lisp, src/package.lisp, src/render.lisp
- Renderer example improvements
+ there is no need for `cl-opengl`, removed `require` form.
+ renderer flag is `:accelerated` not `:render-accelerated`. fixes #103 .
+ Adds a delay in render loop to relax the CPU a bit.
- Adds the function `sdl2:get-render-draw-color`
(P.S. somehow github shows the wrong indentation in diff, you need to view the whole file to check for indentation.)
=> Adds a missing function and renderer example improvement

.gitattributes, src/mouse.lisp, src/package.lisp
- First commit adds .gitattributes file to tell github the repo is common lisp. Without this, repo is marked as a python repo.
- Adds two function `sdl2:get-global-mouse-state` and `sdl2:global-mouse-state-p`. Also corrects the docstring of the function `sdl2:mouse-state-p` to indicate that it works only if the mouse pointer is in a currently focused SDL window.
=> Adds mouse related functions

src/package.lisp
In particular, make sure that they don't use the "COMMON-LISP" package
as this could cause trouble, e.g. a C function taking a parameter
named "T".
=> ensure FFI packages don't use any other packages

src/sdl2.lisp
When quitting, it is possible for `*the-main-thread*` to be a stale thread object and as a consequence for `join-thread` to signal an error.  This patch makes sure to catch it and reset the `*main-thread-channel*`, which is also stale, to `nil` so that it can be re-created when needed.
=> reset the main thread channel on error while joining the main thread

src/rect.lisp
Hello,
I've added a function into rect.lisp that adds intersection checking with a rectangle and a line. Thanks for your support of cl-sdl2.
=> Added intersect-rect-and-line support for SDL_IntersectRectAndLine()

src/events.lisp
[SDL_TextEditingEvent](https://wiki.libsdl.org/SDL_TextEditingEvent) / [SDL_TextInputEvent](https://wiki.libsdl.org/SDL_TextInputEvent) both have a data field `text`, which is `char[32]` in C. 
The current implementation returns a `fixnum` in Lisp.
This PR makes them return as a `string`.
I'm not sure if this is appropriate, but I failed to find way to get the `text` without using [sdl2kit](https://github.com/lispgames/sdl2kit). The sdl2kit CLOP approach feels a little overburden for me. So I am looking for a more simple way to get the text.
May you have a good day and be happy.
=> Make SDL_TextEditingEvent / SDL_TextInputEvent return string as text

src/sdl2.lisp
This pull request addresses a problem where the examples don't run on MacOS. The change prevents the main thread from being interrupted.
How to Reproduce with SBCL:
1. (ql:quickload :sdl2/examples)
2. (sdl2:make-this-thread-main #'sdl2-examples:basic-test)
=> Don't interrupt if the current thread is the main thread

examples/package.lisp, sdl2.asd, src/package.lisp
This PR fixes the following little annoying problem: every time `sdl2` system is loaded, it brings `sdl2-examples` with it, even though it is an empty package with no symbols defined. By having separate `package.lisp` from examples, the [sample code](https://github.com/lispgames/cl-sdl2#running-the-sdl2-examples) from readme is still functional, but `sdl2-examples` is not loaded automatically.
=> Split examples package from the main package

README.md
Redirected to sdl3 guide, but there is nothing available yet. Correct link ↓
<https://wiki.libsdl.org/SDL2/Installation>
=> Fix: SDL2.0 Installation Guide link in README.md

sdl2.asd, src/sdl2.lisp
Currently there is a macro `without-fp-traps` defined in sdl2.lisp, which disables signalling float point exceptions on sbcl only. That at the very least causes problems with loading `sketch` on ccl. The same functionality is defined in `float-features` library, but it also works on abcl, ccl, clasp, clisp, cmucl, ecl and mezzano.
This library is available in quicklisp and is already an indirect dependency of the `#:sdl2/examples` system (cl-opengl uses it).
=> Add portability - use crossplatform float-features:with-float-traps-masked

src/package.lisp, src/video.lisp
Adds a wrapper for SDL_GL_GetDrawableSize(), which is needed to handle hidpi windows.
=> Add gl-get-drawable-size function
